### Importing relevant libraries

In [2]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn import linear_model
import statsmodels.api as sm

In [3]:
# Assigning the value 5 to the variable n, which represents the number of data samples we want to generate.
n = 5

# Generating synthetic regression data using scikit-learn's make_regression function.
X, y = make_regression(n_samples=n, n_features=1, noise=1, random_state=2)

print("X: ", X)
print("y: ", y)
print("size: ", n)

X:  [[-0.05626683]
 [-1.79343559]
 [-0.41675785]
 [-2.1361961 ]
 [ 1.64027081]]
y:  [ -2.65249981 -38.12597924  -9.37063979 -42.8233715   34.30746371]
size:  5


In [4]:
alpha = 0.01
alpha

0.01

In [5]:
# Variable definition
b0 = 1
b1 = 1

print(b0, ", ", b1)

1 ,  1


In [6]:
# Defining a function named yhat that calculates the predicted values (y-hat) for a simple linear regression model.

def yhat(b0, b1, X):
    return b0 + (b1 * X[:, 0])

In [7]:
# Calculating the predicted values (yhat_array) using the yhat function and then computing the error between the true values (y) and the predicted values.

yhat_array = yhat(b0, b1, X)

error = y - yhat_array
print(yhat_array)
print(error)

[ 0.94373317 -0.79343559  0.58324215 -1.1361961   2.64027081]
[ -3.59623298 -37.33254365  -9.95388194 -41.6871754   31.66719291]


In [8]:
# Defining a function named mse (Mean Squared Error) and then calculating the Mean Squared Error between the true values y and the predicted values yhat_array

def mse(y, yhat):
    error = y - yhat
    cost = (1/n) * (np.sum(error) ** 2)
    return cost

mse(y, yhat_array)

741.8263378367806

In [9]:
# Defining a function named gradient_wrt_b0 and then calculating the gradient of the Mean Squared Error (MSE) with respect to the parameter b0 of a linear regression model

def gradient_wrt_b0(error, n):
    return (-2 / n) * np.sum(error)
gradient_wrt_b0(error, n)

24.36105642761464

In [10]:
# Defining a function named gradient_wrt_b1 and then calculating the gradient of the Mean Squared Error (MSE) with respect to the parameter b1 of a linear regression model.

def gradient_wrt_b1(error, X, n):
    return (-2 / n) * np.sum(error * X[:, 0])

gradient_wrt_b1(error, X, n)

-84.91958909873587

In [11]:
# Implementing a simple gradient descent optimization algorithm to update the parameters b0 and b1 of a linear regression model iteratively in order to minimize the Mean Squared Error (MSE). 

iterations = 1000
for i in range(1000):
    yhat_array = yhat(b0, b1, X)
    error = y - yhat_array
    b0 = b0 - alpha * gradient_wrt_b0(error, n)
    b1 = b1 - alpha * gradient_wrt_b1(error, X, n)
    yhat_array = yhat(b0, b1, X)
    cost = mse(y, yhat_array)
    if(i % 100 == 0) | (i == iterations - 1):
        print("iteration: ", i, ", b0: ", b0, " b1: ", b1, " cost: ", cost)

iteration:  0 , b0:  0.7563894357238536  b1:  1.8491958909873587  cost:  657.5471794722478
iteration:  100 , b0:  -1.4792604723081058  b1:  19.975991086944937  cost:  3.0617891874517174
iteration:  200 , b0:  -0.6050592270787869  b1:  20.485476748767947  cost:  0.1801408566456587
iteration:  300 , b0:  -0.4108423119705056  b1:  20.565910408960068  cost:  0.008012694647075663
iteration:  400 , b0:  -0.37000525986221006  b1:  20.582574238067913  cost:  0.00035288871516660474
iteration:  500 , b0:  -0.3614361882333373  b1:  20.5860689114131  cost:  1.5535758558068982e-05
iteration:  600 , b0:  -0.3596382316621167  b1:  20.586802145299735  cost:  6.839444940456353e-07
iteration:  700 , b0:  -0.3592609868109803  b1:  20.58695599132778  cost:  3.01098790501371e-08
iteration:  800 , b0:  -0.3591818338082528  b1:  20.586988271091577  cost:  1.3255531773569308e-09
iteration:  900 , b0:  -0.35916522603270695  b1:  20.586995043987773  cost:  5.835597086016379e-11
iteration:  999 , b0:  -0.3591617

In [12]:
# Fitting a linear regression model to the data and then printing the intercept and coefficients of the fitted model.

X_sklearn = X
model = linear_model.LinearRegression()
model.fit(X_sklearn, y)
print('intercept: ', model.intercept_)
print('coefficients: ', model.coef_)

intercept:  -0.3591608161325244
coefficients:  [20.58699684]


In [13]:
# Reshaping the NumPy array
    
np.array(X.reshape(5,1))

array([[-0.05626683],
       [-1.79343559],
       [-0.41675785],
       [-2.1361961 ],
       [ 1.64027081]])

In [14]:
# Performing Ordinary Least Squares (OLS) linear regression using the Statsmodels library in Python and then printing a summary of the regression results.

X_ols = sm.add_constant(X)
res = stats_model_regression = sm.OLS(y, X_ols).fit()
res.summary()

C:\Users\DELL\anaconda3\anaconda\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.998
Method:                 Least Squares   F-statistic:                     2193.
Date:                Tue, 26 Sep 2023   Prob (F-statistic):           2.14e-05
Time:                        00:43:14   Log-Likelihood:                -7.2344
No. Observations:                   5   AIC:                             18.47
Df Residuals:                       3   BIC:                             17.69
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.3592      0.641     -0.560      0.615      -2.401       1.682
x1            20.5870      0.440     46.833      0.000      19.188      21.986
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.836
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.619
Skew:                           0.376   Prob(JB):                        0.734
Kurtosis:                       1.450   Cond. No.                         1.74
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""